apiVersion: v1
kind: Pod
metadata:
  name: eliot-tools
spec:
  initContainers:
    - name: init-cassandra
      image: busybox
      command: ['sh', '-c', 'until nslookup cassandra-service.default.svc.cluster.local; do echo waiting for cassandra; sleep 2; done; sleep 60']
  containers:
  - name: eliot-tools
    image: iharijono/eliot-tools:latest
    imagePullPolicy: IfNotPresent
    resources:
      # keep request = limit to keep this container in guaranteed class
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
#    command:
#      - tail
#      - -f
#      - /dev/null
    command:
      - /app/visualization/entrypoint.sh
      - -g
      - "5"
      - -s
      - "10"
      - -gp
      - S
      - -sp
      - ID
    #
    # BEING USED currently by Registry
    #
    env:
    - name: ELIOT_SIM_KAFKA_BOOTSTRAPPER
      value: bootstrap.default.svc.cluster.local:9092
    - name: ELIOT_INFLUXDB_URL
      value: http://influxdb-service.default.svc.cluster.local:8086
    - name: ELIOT_INFLUXDB_HOST
      value: influxdb-service.default.svc.cluster.local
    - name: ELIOT_FLINK_JOBMANAGER_HOST
      value: flink-jobmanager.default.svc.cluster.local:8081
    - name: ELIOT_CASSANDRA_URL
      value: http://cassandra-service.default.svc.cluster.local:8086
    - name: ELIOT_SIM_KAFKA_IN_TOPIC
      value: in-topic
    - name: ELIOT_SIM_REST_URL
      value: http://eliot-service.default.svc.cluster.local:6666
    - name: ELIOT_SIM_DURATION
      value: 5m
    - name: ELIOT_SIM_GW_NUMBER
      value: "1"
    - name: ELIOT_SIM_SENSOR_NUMBER
      value: "5"
    - name: ELIOT_SIM_VERBOSE
      value: "False"

