apiVersion: batch/v1
kind: Job
metadata:
  name: eliot-simulator-unregistered
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: eliot-simulator
        tier: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: eliot-simulator-unregistered
          image: iharijono/eliot-tools:latest
          imagePullPolicy: IfNotPresent
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
          command:
            - /app/visualization/run_sim.sh
          env:
            - name: ELIOT_SIM_KAFKA_BOOTSTRAPPER
              value: bootstrap.default.svc.cluster.local:9092
            - name: ELIOT_INFLUXDB_URL
              value: http://influxdb-service.default.svc.cluster.local:8086
            - name: ELIOT_INFLUXDB_HOST
              value: influxdb-service.default.svc.cluster.local
            - name: ELIOT_FLINK_JOBMANAGER_HOST
              value: flink-jobmanager.default.svc.cluster.local:8081
            - name: ELIOT_CASSANDRA_URL
              value: http://cassandra-service.default.svc.cluster.local:8086
            - name: ELIOT_SIM_KAFKA_IN_TOPIC
              value: in-topic
            - name: ELIOT_SIM_REST_URL
              value: http://eliot-service.default.svc.cluster.local:6666
            - name: ELIOT_SIM_DURATION
              value: 5m
            - name: ELIOT_SIM_GW_NUMBER
              value: "5"
            - name: ELIOT_SIM_SENSOR_NUMBER
              value: "10"
            - name: ELIOT_SIM_GW_PREFIX
              value: "ST"
            - name: ELIOT_SIM_SENSOR_PREFIX
              value: "UNREGISTERED"
            - name: ELIOT_SIM_VERBOSE
              value: "False"

