{
 "title": "Row",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Exporter Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}
{
 "title": "Flink Metrics",
 "description": "Flink Metrics (with Kafka) on K8S\nThis dashboard if for monitoring Flink Applications Performance. It includes metrics like record count, latency. It also has kafka parameters like bytes count. Moreover, it has k8s memory, CPU and Network statistics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": "label_values(kafka_log_logstartoffset, topic)"
   },
   {
    "name": "Broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_log_size, instance)"
   },
   {
    "name": "Zookeeper",
    "label": "Kafka Zookeeper",
    "query": "label_values(zookeeper_InitLimit,instance)"
   },
   {
    "name": "Flink_Job_Name",
    "query": "label_values(flink_jobmanager_job_uptime,job_name)"
   },
   {
    "name": "Source",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Sink",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pods",
    "query": "label_values(kube_pod_container_info,pod)"
   }
  ]
 },
 "panels": [
  { "title": "Job Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Records In - Source",
   "type": "graph",
   "description": "Records in per minute",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Number of Records" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=~\"$Flink_Job_Name\",task_name=\"$Source\"})",
     "legendFormat": "Records In "
    }
   ]
  },
  {
   "title": "Records In (Current)",
   "type": "singlestat",
   "description": "Current - Records In\nIt's the rate over last 2 minutes.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsIn{job_name=~\"$Flink_Job_Name\",task_name=\"$Source\"}[2m]))"
    }
   ]
  },
  {
   "title": "Messages in rate per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_messagesin_total{topic!=\"\",topic=~\"$Topics\",instance=~\"$Broker\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records in - Sink",
   "type": "graph",
   "description": "Records out per minute is equal to Records in per minute in Sink",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Number of Records" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=~\"$Flink_Job_Name\",task_name=\"$Sink\"})",
     "legendFormat": "Records Out"
    }
   ]
  },
  {
   "title": "Kafka - Bytes in rate per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesin_total{topic!=\"\",topic=~\"$Topics\",instance=~\"$Broker\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records In - Sink (Current)",
   "type": "singlestat",
   "description": "Current - Records Out\nIt's the rate over last 2 minutes.\n\nRecords Out for the application is equal to records in for the sink",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsIn{job_name=~\"$Flink_Job_Name\",task_name=\"$Sink\"}[2m]))"
    }
   ]
  },
  {
   "title": "Kafka - Bytes out rate per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesout_total{topic!=\"\",topic=~\"$Topics\",instance=~\"$Broker\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Source to Sink Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Maximum Latency"
    },
    {
     "expr": "min(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Minimum Latency"
    },
    {
     "expr": "avg(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Average Latency"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Input Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_buffers_inputQueueLength{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Input Queue Length"
    }
   ]
  },
  {
   "title": "Output Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_buffers_outputQueueLength{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Output Queue Length"
    }
   ]
  },
  {
   "title": "Pod network I/O (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\"$Pods\"}[2m])) by (pod_name) + sum (rate (container_network_transmit_bytes_total{pod_name=~\"$Pods\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    }
   ]
  },
  { "title": "Memory & CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Containers CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"$Pods\"}[2m])) by (pod_name)",
     "legendFormat": "pod: {{ pod_name }} "
    }
   ]
  },
  {
   "title": "Containers Memory usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod_name=~\"$Pods\"}) by (pod_name)",
     "legendFormat": "pod: {{ pod_name }} "
    }
   ]
  },
  {
   "title": "JobManager Buffers",
   "type": "graph",
   "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_Count",
     "legendFormat": "Used "
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity",
     "legendFormat": "Available "
    }
   ]
  },
  {
   "title": "Taskmanager Buffers",
   "type": "graph",
   "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_Count)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "JobManager Heap Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "Used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "TaskManager Heap Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Max)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100*flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "JobManager"
    },
    {
     "expr": "100 * flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "TaskManager"
    }
   ]
  },
  {
   "title": "CPU Load - JobManager",
   "type": "singlestat",
   "description": "It's the rate over last 2 minutes.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 49 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_jobmanager_Status_JVM_CPU_Load[2m]))"
    }
   ]
  },
  {
   "title": "CPU Load - TaskManager",
   "type": "singlestat",
   "description": "It's the rate over last 2 minutes.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 54 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_Status_JVM_CPU_Load[2m]))"
    }
   ]
  }
 ]
}
{
 "title": "Flink Everest Analytics Job",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "JobManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "heap memory [{{instance}}]"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
       "legendFormat": "non-heap memory [{{instance}}]"
      }
     ]
    },
    {
     "title": "GC Overhead",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time[5m])/1000 + rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time[5m])/1000",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TaskManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "heap memory [{{instance}}]"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
       "legendFormat": "non-heap memory [{{instance}}]"
      }
     ]
    },
    {
     "title": "GC Overhead",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[5m])/1000 + rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[5m])/1000",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Everest Analytics Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Network IO (Kb per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_network_io_rate{job_name=\"Flink_Everest_Job\"})",
     "legendFormat": "{{Network IO}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_cpu_hroughput{job_name=\"Flink_Everest_Job\"}) * 60",
     "legendFormat": "{{CPU Data Throughput data/sec}}"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInLocalPerSecond{job_name=\"Flink_Everest_Job\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond{job_name=\"$job\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Everest Monitored Cluster Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_cluster_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 5 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EliotMetrics_pod_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with critical category of CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 5 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EliotMetrics_cpu_critical_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with Category low of CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 5 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EliotMetrics_cpu_low_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with category low of MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_mem_low_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with high usage of MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_mem_high_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with category of critical in NETWORK",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_net_critical_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with the category of High usage of NETWORK",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 10 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_net_high_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with category of regular usage of NETWORK",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EliotMetrics_net_regular_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{job_name=\"$job\"}"
    }
   ]
  },
  {
   "title": "Number of Pods with category high in usage of CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 15 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_cpu_high_numbers{job_name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Pods with category of regular usage of MEMORY ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 15 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_EverestMetrics_mem_regular_numbers{job_name=\"$job\"})"
    }
   ]
  }
 ]
}
{
 "title": "Network I/O pressure",
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}
{
 "title": "Total usage",
 "panels": [
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  }
 ]
}
{
 "title": "Pods CPU usage",
 "panels": [
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "System services CPU usage",
 "panels": [
  {
   "title": "System services CPU usage (1m avg)",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Containers CPU usage",
 "panels": [
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  }
 ]
}
{
 "title": "All processes CPU usage",
 "panels": [
  {
   "title": "All processes CPU usage (1m avg)",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  }
 ]
}
{
 "title": "Pods memory usage",
 "panels": [
  {
   "title": "Pods memory usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "System services memory usage",
 "panels": [
  {
   "title": "System services memory usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Containers memory usage",
 "panels": [
  {
   "title": "Containers memory usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  }
 ]
}
{
 "title": "All processes memory usage",
 "panels": [
  {
   "title": "All processes memory usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  }
 ]
}
{
 "title": "Pods network I/O",
 "panels": [
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Containers network I/O",
 "panels": [
  {
   "title": "Containers network I/O (1m avg)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  }
 ]
}
{
 "title": "All processes network I/O",
 "panels": [
  {
   "title": "All processes network I/O (1m avg)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}