apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: everest
  labels:
    app: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
        component: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: web-ui
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        env:
        - name: GF_INSTALL_PLUGINS
          value: "grafana-kubernetes-app,grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource"
        # - name: GF_AUTH_BASIC_ENABLED
        #   value: "true"
        # - name: GF_SECURITY_ADMIN_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: grafana
        #       key: admin-username
        # - name: GF_SECURITY_ADMIN_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: grafana
        #       key: admin-password
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: ds-configmap-prom
          mountPath: /etc/grafana/provisioning/datasources/prom-datasource.yaml
          subPath: prom-datasource.yaml
        - name: db-configmap-all
          mountPath: /etc/grafana/provisioning/dashboards/all-dashboard.yaml
          subPath: all-dashboard.yaml
        - name: dashboard-configmap
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: ds-configmap-prom
        configMap:
          name: grafana-ds-config
      - name: db-configmap-all
        configMap:
          name: grafana-ds-config
      - name: dashboard-configmap
        configMap:
          name: grafana-dashboard-config
