apiVersion: v1
kind: Pod
metadata:
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  containers:
  - name: kafka-exporter
    image: danielqsj/kafka-exporter:latest
    args:
      - --kafka.server=bootstrap.default.svc.cluster.local:9092
    ports:
    - containerPort: 9308
      name: exporter
    resources:
      # keep request = limit to keep this container in guaranteed class
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
