apiVersion: v1
kind: Pod
metadata:
  name: everest-analytics
spec:
  # initContainers:
  #   - name: init-cassandra
  #     image: busybox
  #     command: ['sh', '-c', 'until nslookup cassandra-service.default.svc.cluster.local; do echo waiting for cassandra; sleep 2; done; sleep 60']
  containers:
  - name: everest-analytics
    image: iharijono/everest-flink-analytics:latest
    imagePullPolicy: Always
    resources:
      # keep request = limit to keep this container in guaranteed class
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
#    command:
#      - tail
#      - -f
#      - /dev/null
    command:
      - /app/pipeline/everest_cmd.sh
    #
    # TBD
    #
    env:
    - name: EVEREST_FLINK_JOBMANAGER_HOST
      value: flink-jobmanager.everest.svc.cluster.local:8081
    # - name: EVEREST_SIM_KAFKA_BOOTSTRAPPER
    #   value: bootstrap.kafka.svc.cluster.local:9092

