{
 "title": "Eliot SensorData",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "measures", "label": "Measurement", "query": "show measurements" },
   {
    "name": "sensorid",
    "label": "Sensor ID",
    "query": "SHOW TAG VALUES WITH KEY = \"sensorid\""
   }
  ]
 },
 "panels": [
  {
   "title": "CRITICAL SENSORS",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorid",
     "groupBy": [
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "critical",
     "select": [
      [
       { "params": [ "absdiff" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Risk Sensors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorid",
     "groupBy": [
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "high",
     "select": [
      [
       { "params": [ "absdiff" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Low Risk Sensors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorid",
     "groupBy": [
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "low",
     "select": [
      [
       { "params": [ "absdiff" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Value of All Sensor in the window (only for Debugging)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorid",
     "groupBy": [
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "maxsensors",
     "select": [
      [
       { "params": [ "absdiff" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Sensor (only for Debugging)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorid",
     "groupBy": [
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "absdiff" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}