{
 "title": "Flink Metrics",
 "description": "Flink Metrics (with Kafka) on K8S\nThis dashboard if for monitoring Flink Applications Performance. It includes metrics like record count, latency. It also has kafka parameters like bytes count. Moreover, it has k8s memory, CPU and Network statistics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": "label_values(kafka_log_logstartoffset, topic)"
   },
   {
    "name": "Broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_log_size, instance)"
   },
   {
    "name": "Zookeeper",
    "label": "Kafka Zookeeper",
    "query": "label_values(zookeeper_InitLimit,instance)"
   },
   {
    "name": "Flink_Job_Name",
    "query": "label_values(flink_jobmanager_job_uptime,job_name)"
   },
   {
    "name": "Source",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Sink",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pods",
    "query": "label_values(kube_pod_container_info,pod)"
   }
  ]
 },
 "panels": [
  { "title": "Job Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Records In - Source",
   "type": "graph",
   "description": "Records in per minute",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Number of Records" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=~\"$Flink_Job_Name\",task_name=\"$Source\"})",
     "legendFormat": "Records In "
    }
   ]
  },
  {
   "title": "Records In (Current)",
   "type": "singlestat",
   "description": "Current - Records In\nIt's the rate over last 2 minutes.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsIn{job_name=~\"$Flink_Job_Name\",task_name=\"$Source\"}[2m]))"
    }
   ]
  },
  {
   "title": "Messages in rate per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_messagesin_total{topic!=\"\",topic=~\"$Topics\",instance=~\"$Broker\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records in - Sink",
   "type": "graph",
   "description": "Records out per minute is equal to Records in per minute in Sink",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Number of Records" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=~\"$Flink_Job_Name\",task_name=\"$Sink\"})",
     "legendFormat": "Records Out"
    }
   ]
  },
  {
   "title": "Kafka - Bytes in rate per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesin_total{topic!=\"\",topic=~\"$Topics\",instance=~\"$Broker\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records In - Sink (Current)",
   "type": "singlestat",
   "description": "Current - Records Out\nIt's the rate over last 2 minutes.\n\nRecords Out for the application is equal to records in for the sink",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsIn{job_name=~\"$Flink_Job_Name\",task_name=\"$Sink\"}[2m]))"
    }
   ]
  },
  {
   "title": "Kafka - Bytes out rate per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesout_total{topic!=\"\",topic=~\"$Topics\",instance=~\"$Broker\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Source to Sink Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Maximum Latency"
    },
    {
     "expr": "min(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Minimum Latency"
    },
    {
     "expr": "avg(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Average Latency"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Input Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_buffers_inputQueueLength{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Input Queue Length"
    }
   ]
  },
  {
   "title": "Output Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_buffers_outputQueueLength{job_name=~\"$Flink_Job_Name\"})",
     "legendFormat": "Output Queue Length"
    }
   ]
  },
  {
   "title": "Pod network I/O (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\"$Pods\"}[2m])) by (pod_name) + sum (rate (container_network_transmit_bytes_total{pod_name=~\"$Pods\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    }
   ]
  },
  { "title": "Memory & CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Containers CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"$Pods\"}[2m])) by (pod_name)",
     "legendFormat": "pod: {{ pod_name }} "
    }
   ]
  },
  {
   "title": "Containers Memory usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod_name=~\"$Pods\"}) by (pod_name)",
     "legendFormat": "pod: {{ pod_name }} "
    }
   ]
  },
  {
   "title": "JobManager Buffers",
   "type": "graph",
   "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_Count",
     "legendFormat": "Used "
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity",
     "legendFormat": "Available "
    }
   ]
  },
  {
   "title": "Taskmanager Buffers",
   "type": "graph",
   "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_Count)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "JobManager Heap Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "Used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "TaskManager Heap Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Max)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100*flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "JobManager"
    },
    {
     "expr": "100 * flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "TaskManager"
    }
   ]
  },
  {
   "title": "CPU Load - JobManager",
   "type": "singlestat",
   "description": "It's the rate over last 2 minutes.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 49 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_jobmanager_Status_JVM_CPU_Load[2m]))"
    }
   ]
  },
  {
   "title": "CPU Load - TaskManager",
   "type": "singlestat",
   "description": "It's the rate over last 2 minutes.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 54 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_Status_JVM_CPU_Load[2m]))"
    }
   ]
  }
 ]
}