apiVersion: v1
kind: Service
metadata:
  name: flink-dns
spec:
  ports:
  - port: 9250
  # [podname].flink-manager.default.svc.cluster.local
  clusterIP: None
  selector:
    app: flink
    component: taskmanager
