apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-outside
spec:
  ports:
  - protocol: TCP
    targetPort: 8081
    port: 30081
    nodePort: 30081
  type: NodePort 
  selector:
    app: flink
    component: jobmanager
