kind: Service
apiVersion: v1
metadata:
  name: prometheus-nodeport
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    targetPort: 9090
    port: 32000
    nodePort: 32000
  type: NodePort